name: Go
on:
    push:
        branches: ["*"]
    pull_request:
        branches: [ "master" ]

jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.6'
        
        - name: Unit Test
          run: go test -v ./...

    release:
      runs-on: ubuntu-latest
      steps:
        - name: Push docker image
          run: echo Push to docker image
